export const CURRENCIES = {
  BTC: { symbol: '₿', name: 'Bitcoin', color: 'from-yellow-400 to-yellow-600', icon: '₿' },
  ETH: { symbol: 'Ξ', name: 'Ethereum', color: 'from-blue-400 to-blue-600', icon: 'Ξ' },
  PI: { symbol: 'Π', name: 'Pi Network', color: 'from-purple-400 to-purple-600', icon: 'Π' },
  USDT: { symbol: '₮', name: 'USDT', color: 'from-green-400 to-green-600', icon: '₮' },
  USD: { symbol: '$', name: 'US Dollar', color: 'from-emerald-400 to-emerald-600', icon: '$' },
  EUR: { symbol: '€', name: 'Euro', color: 'from-blue-500 to-blue-700', icon: '€' },
  GBP: { symbol: '£', name: 'British Pound', color: 'from-red-400 to-red-600', icon: '£' },
  JPY: { symbol: '¥', name: 'Japanese Yen', color: 'from-red-300 to-red-500', icon: '¥' },
  CHF: { symbol: 'CHF', name: 'Swiss Franc', color: 'from-red-600 to-red-800', icon: 'CHF' },
  CAD: { symbol: 'C$', name: 'Canadian Dollar', color: 'from-red-500 to-rose-600', icon: 'C$' },
  AUD: { symbol: 'A$', name: 'Australian Dollar', color: 'from-yellow-500 to-orange-600', icon: 'A$' },
  SGD: { symbol: 'S$', name: 'Singapore Dollar', color: 'from-red-600 to-orange-700', icon: 'S$' },
  HKD: { symbol: 'HK$', name: 'Hong Kong Dollar', color: 'from-red-500 to-red-700', icon: 'HK$' },
  INR: { symbol: '₹', name: 'Indian Rupee', color: 'from-orange-400 to-orange-600', icon: '₹' },
  ZAR: { symbol: 'R', name: 'South African Rand', color: 'from-yellow-600 to-orange-700', icon: 'R' },
  TZS: { symbol: 'TSh', name: 'Tanzanian Shilling', color: 'from-slate-600 to-slate-800', icon: 'TSh' },
  KES: { symbol: 'KSh', name: 'Kenyan Shilling', color: 'from-green-600 to-green-800', icon: 'KSh' },
};

export const LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'sw', name: 'Kiswahili', flag: '🇹🇿' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'pt', name: 'Português', flag: '🇧🇷' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
];

export const CURRENCY_RATES: Record<string, number> = {
  BTC: 65420.50,
  ETH: 3450.75,
  PI: 24.75,
  USDT: 1.00,
  USD: 1.00,
  EUR: 0.92,
  GBP: 0.79,
  JPY: 149.50,
  CHF: 0.88,
  CAD: 1.36,
  AUD: 1.53,
  SGD: 1.34,
  HKD: 7.81,
  INR: 83.12,
  ZAR: 18.50,
  TZS: 2621.50,
  KES: 130.45,
};
